// src/components/Header/index.tsx

import React from 'react';

import { Link } from 'react-router-dom';

import { Container } from './styles';

import logo from '../../utils/logo2.png';



const Header: React.FC = () => (
  <Container>
    <header>
     
      <nav>
       
        <Link to="/">  
        <img alt = "logo"src = {logo}></img>
        </Link>
      </nav>
    </header>
  </Container>
);

export default Header;

// src/components/Header.vue
<template>
  <header>
    <nav>
      <router-link to="/">
        <img src="../assets/logo.png" class="logo" alt="SpaceX" />
      </router-link>
    </nav>
  </header>
</template>

<script>
export default {
  name: "Header",
};
</script>

<style scoped>
header {
  background-color: var(--dark);
  position: fixed;
  width: 100%;
  text-align: center;
  flex: 1;
}

nav {
  padding: 1rem;
}

.logo {
  width: 200px;
}
</style>
